language: node_js
node_js:
  - "6"
install:
  - node --version
  - npm --version
  - npm install -g babel-cli
  - npm install
os:
  - linux
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
